version: "3.9"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  botcore:
    <<: *logging
    <<: *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: botcore

    volumes:
      - ./logs:/bot/logs
      - .:/bot:ro

    env_file:
      - .env
